<?php

declare(strict_types=1);

/*
 * PAM Material component specification.
 *
 * This is an authored PAM source file, not imported metadata. Public tags use
 * the p-* namespace while PHP facades use the equivalent P* class names.
 *
 * Each component type is a sequential integer. Keep existing values stable and
 * append new entries only.
 *
 * @return list<array{
 *     type: int,
 *     module: string,
 *     components: list<string>,
 *     mobile?: bool,
 * }>
 */
return [
    ['type' => 1, 'module' => 'app', 'components' => ['PApp'], 'mobile' => false],
    ['type' => 2, 'module' => 'app-bar', 'components' => ['PAppBar', 'PAppBarNavIcon', 'PAppBarTitle']],
    ['type' => 3, 'module' => 'alert', 'components' => ['PAlert', 'PAlertTitle']],
    ['type' => 4, 'module' => 'autocomplete', 'components' => ['PAutocomplete']],
    ['type' => 5, 'module' => 'avatar', 'components' => ['PAvatar']],
    ['type' => 6, 'module' => 'badge', 'components' => ['PBadge']],
    ['type' => 7, 'module' => 'banner', 'components' => ['PBanner', 'PBannerText', 'PBannerActions']],
    ['type' => 8, 'module' => 'bottom-navigation', 'components' => ['PBottomNavigation'], 'mobile' => false],
    ['type' => 9, 'module' => 'bottom-sheet', 'components' => ['PBottomSheet']],
    ['type' => 10, 'module' => 'breadcrumbs', 'components' => ['PBreadcrumbs', 'PBreadcrumbsItem', 'PBreadcrumbsDivider']],
    ['type' => 11, 'module' => 'button', 'components' => ['PBtn']],
    ['type' => 12, 'module' => 'button-group', 'components' => ['PBtnGroup']],
    ['type' => 13, 'module' => 'button-toggle', 'components' => ['PBtnToggle']],
    ['type' => 14, 'module' => 'calendar', 'components' => ['PCalendar', 'PCalendarDay', 'PCalendarHeader', 'PCalendarInterval']],
    ['type' => 15, 'module' => 'card', 'components' => ['PCard', 'PCardItem', 'PCardTitle', 'PCardSubtitle', 'PCardText', 'PCardActions']],
    ['type' => 16, 'module' => 'carousel', 'components' => ['PCarousel', 'PCarouselItem']],
    ['type' => 17, 'module' => 'checkbox', 'components' => ['PCheckbox', 'PCheckboxBtn']],
    ['type' => 18, 'module' => 'chip', 'components' => ['PChip']],
    ['type' => 19, 'module' => 'chip-group', 'components' => ['PChipGroup']],
    ['type' => 20, 'module' => 'code', 'components' => ['PCode'], 'mobile' => false],
    ['type' => 21, 'module' => 'color-input', 'components' => ['PColorInput']],
    ['type' => 22, 'module' => 'color-picker', 'components' => ['PColorPicker', 'PColorPickerCanvas', 'PColorPickerEdit', 'PColorPickerPreview', 'PColorPickerSwatches']],
    ['type' => 23, 'module' => 'combobox', 'components' => ['PCombobox']],
    ['type' => 24, 'module' => 'confirm-edit', 'components' => ['PConfirmEdit']],
    ['type' => 25, 'module' => 'counter', 'components' => ['PCounter']],
    ['type' => 26, 'module' => 'data-iterator', 'components' => ['PDataIterator']],
    ['type' => 27, 'module' => 'data-table', 'components' => ['PDataTable', 'PDataTableServer', 'PDataTableVirtual']],
    ['type' => 28, 'module' => 'date-input', 'components' => ['PDateInput']],
    ['type' => 29, 'module' => 'date-picker', 'components' => ['PDatePicker', 'PDatePickerControls', 'PDatePickerHeader', 'PDatePickerMonth', 'PDatePickerMonths', 'PDatePickerYears']],
    ['type' => 30, 'module' => 'defaults-provider', 'components' => ['PDefaultsProvider']],
    ['type' => 31, 'module' => 'dialog', 'components' => ['PDialog']],
    ['type' => 32, 'module' => 'divider', 'components' => ['PDivider']],
    ['type' => 33, 'module' => 'empty-state', 'components' => ['PEmptyState']],
    ['type' => 34, 'module' => 'expansion-panels', 'components' => ['PExpansionPanels', 'PExpansionPanel', 'PExpansionPanelTitle', 'PExpansionPanelText']],
    ['type' => 35, 'module' => 'fab', 'components' => ['PFab']],
    ['type' => 36, 'module' => 'field', 'components' => ['PField', 'PFieldLabel']],
    ['type' => 37, 'module' => 'file-input', 'components' => ['PFileInput']],
    ['type' => 38, 'module' => 'file-upload', 'components' => ['PFileUpload', 'PFileUploadItem']],
    ['type' => 39, 'module' => 'footer', 'components' => ['PFooter'], 'mobile' => false],
    ['type' => 40, 'module' => 'form', 'components' => ['PForm']],
    ['type' => 41, 'module' => 'grid', 'components' => ['PContainer', 'PRow', 'PCol', 'PSpacer']],
    ['type' => 42, 'module' => 'hotkey', 'components' => ['PHotkey'], 'mobile' => false],
    ['type' => 43, 'module' => 'hover', 'components' => ['PHover'], 'mobile' => false],
    ['type' => 44, 'module' => 'icon', 'components' => ['PIcon']],
    ['type' => 45, 'module' => 'icon-button', 'components' => ['PIconBtn']],
    ['type' => 46, 'module' => 'image', 'components' => ['PImg']],
    ['type' => 47, 'module' => 'infinite-scroll', 'components' => ['PInfiniteScroll']],
    ['type' => 48, 'module' => 'input', 'components' => ['PInput']],
    ['type' => 49, 'module' => 'item-group', 'components' => ['PItemGroup', 'PItem']],
    ['type' => 50, 'module' => 'keyboard-key', 'components' => ['PKbd'], 'mobile' => false],
    ['type' => 51, 'module' => 'label', 'components' => ['PLabel']],
    ['type' => 52, 'module' => 'layout', 'components' => ['PLayout', 'PLayoutItem'], 'mobile' => false],
    ['type' => 53, 'module' => 'lazy', 'components' => ['PLazy']],
    ['type' => 54, 'module' => 'list', 'components' => ['PList', 'PListItem', 'PListItemTitle', 'PListItemSubtitle', 'PListGroup', 'PListSubheader']],
    ['type' => 55, 'module' => 'locale-provider', 'components' => ['PLocaleProvider']],
    ['type' => 56, 'module' => 'main', 'components' => ['PMain'], 'mobile' => false],
    ['type' => 57, 'module' => 'menu', 'components' => ['PMenu']],
    ['type' => 58, 'module' => 'messages', 'components' => ['PMessages']],
    ['type' => 59, 'module' => 'navigation-drawer', 'components' => ['PNavigationDrawer'], 'mobile' => false],
    ['type' => 60, 'module' => 'number-input', 'components' => ['PNumberInput']],
    ['type' => 61, 'module' => 'otp-input', 'components' => ['POtpInput']],
    ['type' => 62, 'module' => 'overlay', 'components' => ['POverlay']],
    ['type' => 63, 'module' => 'pagination', 'components' => ['PPagination']],
    ['type' => 64, 'module' => 'parallax', 'components' => ['PParallax']],
    ['type' => 65, 'module' => 'picker', 'components' => ['PPicker', 'PPickerTitle']],
    ['type' => 66, 'module' => 'progress-circular', 'components' => ['PProgressCircular']],
    ['type' => 67, 'module' => 'progress-linear', 'components' => ['PProgressLinear']],
    ['type' => 68, 'module' => 'pull-to-refresh', 'components' => ['PPullToRefresh'], 'mobile' => false],
    ['type' => 69, 'module' => 'radio', 'components' => ['PRadio']],
    ['type' => 70, 'module' => 'radio-group', 'components' => ['PRadioGroup']],
    ['type' => 71, 'module' => 'range-slider', 'components' => ['PRangeSlider']],
    ['type' => 72, 'module' => 'rating', 'components' => ['PRating']],
    ['type' => 73, 'module' => 'responsive', 'components' => ['PResponsive'], 'mobile' => false],
    ['type' => 74, 'module' => 'select', 'components' => ['PSelect']],
    ['type' => 75, 'module' => 'selection-control', 'components' => ['PSelectionControl']],
    ['type' => 76, 'module' => 'selection-control-group', 'components' => ['PSelectionControlGroup']],
    ['type' => 77, 'module' => 'sheet', 'components' => ['PSheet']],
    ['type' => 78, 'module' => 'skeleton-loader', 'components' => ['PSkeletonLoader']],
    ['type' => 79, 'module' => 'slide-group', 'components' => ['PSlideGroup', 'PSlideGroupItem']],
    ['type' => 80, 'module' => 'slider', 'components' => ['PSlider']],
    ['type' => 81, 'module' => 'snackbar', 'components' => ['PSnackbar']],
    ['type' => 82, 'module' => 'snackbar-queue', 'components' => ['PSnackbarQueue']],
    ['type' => 83, 'module' => 'sparkline', 'components' => ['PSparkline']],
    ['type' => 84, 'module' => 'speed-dial', 'components' => ['PSpeedDial']],
    ['type' => 85, 'module' => 'stepper', 'components' => ['PStepper', 'PStepperHeader', 'PStepperItem', 'PStepperWindow', 'PStepperWindowItem', 'PStepperActions']],
    ['type' => 86, 'module' => 'stepper-vertical', 'components' => ['PStepperVertical', 'PStepperVerticalItem', 'PStepperVerticalActions']],
    ['type' => 87, 'module' => 'switch', 'components' => ['PSwitch']],
    ['type' => 88, 'module' => 'system-bar', 'components' => ['PSystemBar'], 'mobile' => false],
    ['type' => 89, 'module' => 'table', 'components' => ['PTable'], 'mobile' => false],
    ['type' => 90, 'module' => 'tabs', 'components' => ['PTabs', 'PTab']],
    ['type' => 91, 'module' => 'text', 'components' => ['PText']],
    ['type' => 92, 'module' => 'text-field', 'components' => ['PTextField']],
    ['type' => 93, 'module' => 'textarea', 'components' => ['PTextarea']],
    ['type' => 94, 'module' => 'theme-provider', 'components' => ['PThemeProvider']],
    ['type' => 95, 'module' => 'time-picker', 'components' => ['PTimePicker', 'PTimePickerClock', 'PTimePickerControls']],
    ['type' => 96, 'module' => 'timeline', 'components' => ['PTimeline', 'PTimelineItem']],
    ['type' => 97, 'module' => 'toolbar', 'components' => ['PToolbar', 'PToolbarTitle', 'PToolbarItems']],
    ['type' => 98, 'module' => 'tooltip', 'components' => ['PTooltip']],
    ['type' => 99, 'module' => 'treeview', 'components' => ['PTreeview', 'PTreeviewItem']],
    ['type' => 100, 'module' => 'validation', 'components' => ['PValidation']],
    ['type' => 101, 'module' => 'virtual-scroll', 'components' => ['PVirtualScroll'], 'mobile' => false],
    ['type' => 102, 'module' => 'window', 'components' => ['PWindow', 'PWindowItem']],
    ['type' => 103, 'module' => 'transition', 'components' => ['PTransition']],
];
